### PR TITLE
Fix Sea Emperor hatching sequence not completing in multiplayer

### LINKED ISSUE #2051: Please write an informative title describing the bug in a few words
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

The Sea Emporer Hatching event failed to play, stalling the final progression and unable to continue. 
Login and Logout caused many things to fail: 
Hatching Platform Floating
juvional Sea Emporer dont swim up
All vehicles exploding. 

### Describe the steps you took to encounter the bug.

Start hatching Event
All Players Login Logout
All Players Logout
Server restart
All Players Login. 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by misterbubb**
Closes #2051 

The hatching sequence was failing because the original patch wasn't calling `StartHatchAnimation()`, which is needed to trigger the animation callback chain that calls `SwimToMother()`.

Changes:
- IncubatorEgg_HatchNow_Patch: Simulating player now spawns baby, attaches it to the egg's attach point, broadcasts the entity, and runs the full animation sequence via `StartHatchAnimation()`
- SeaEmperorBaby_Start_Patch: New patch that handles remotely spawned babies (via server broadcast) by making them swim to mother if they have no parent (meaning they weren't spawned by the local hatching sequence)

## How to test

1. Teleport 2 players to
```
warp 280 -1612 -374
```
2. Add items to inventory:
```
item precursorioncrystal 2
item hatchingenzymes
```
3. Use terminals and see animations play

### CODE REVIEW

File: NitroxPatcher/Patches/Dynamic/IncubatorEgg_HatchNow_Patch.cs [hunk 1]
```diff
@@ -1,53 +1,71 @@
...
-        SafeAnimator.SetBool(egg.animationController.eggAnimator, egg.animParameter, true);
-    }
-
-    private static void SpawnBabiesIfSimulating(IncubatorEgg egg)
-    {
-        SimulationOwnership simulationOwnership = NitroxServiceLocator.LocateService<SimulationOwnership>();
-
-        NitroxEntity serverKnownParent = egg.GetComponentInParent<NitroxEntity>();
+        NitroxEntity serverKnownParent = __instance.GetComponentInParent<NitroxEntity>();
         Validate.NotNull(serverKnownParent, "Could not find a server known parent for incubator egg");
```
Comment (Measurity) [inline NitroxPatcher/Patches/Dynamic/IncubatorEgg_HatchNow_Patch.cs]: Let's change the Validate.NotNull as well to an `if () { return; }` exit. Throwing exceptions (what `Validate.NotNull` does) in game code has caused unforeseen bugs before.

File: NitroxPatcher/Patches/Dynamic/IncubatorEgg_HatchNow_Patch.cs [hunk 2]
```diff
@@ -1,53 +1,75 @@
...
 using Nitrox.Model.Subnautica.DataStructures.GameLogic.Entities;
 using UnityEngine;
 
 namespace NitroxPatcher.Patches.Dynamic;
 
+/// <summary>
+/// Handles the Sea Emperor baby hatching sequence in multiplayer.
+/// The simulating player spawns the babies and broadcasts them to other players.
+/// The simulating player also runs the full animation sequence which triggers SwimToMother().
+/// Non-simulating players just see the egg animation - their babies are spawned via server
```
Comment (Coding-Hen) [inline NitroxPatcher/Patches/Dynamic/IncubatorEgg_HatchNow_Patch.cs]: Do we not want this animation to be the full one for all players if we can or do we intentionally not want it to play for multiple players?

**Review by Measurity — APPROVED** [review]
Hatching works and they go to the portal (even if portal is not active, but might be vanilla thing).

The SwimToMother behavior I don't see in game (probably because the mother isn't properly synced). The babies just float above their shells and then go through portal.

File: NitroxPatcher/Patches/Dynamic/IncubatorEggAnimation_OnHatchAnimationEnd_Patch.cs [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+            // For temporary babies, we only want to end the cinematic mode and cleanup
+            // Don't call SwimToMother() as that should only happen for the real networked baby
+            __instance.baby.cinematicController.SetCinematicMode(false);
+            
+            // Use reflection to safely set the animationActive field to false
+            FieldInfo animationActiveField = typeof(IncubatorEggAnimation).GetField("animationActive", BindingFlags.NonPublic | BindingFlags.Instance);
+            if (animationActiveField != null)
+            {
+                animationActiveField.SetValue(__instance, false);
+            }
```
Comment (dartasen) [inline NitroxPatcher/Patches/Dynamic/IncubatorEggAnimation_OnHatchAnimationEnd_Patch.cs]: Since we're publicizing assemblies, you should be able to do : 

```cs
__instance.animationActive = false;
```

File: NitroxPatcher/Patches/Dynamic/IncubatorEgg_HatchNow_Patch.cs [hunk 4]
```diff
@@ -55,21 +54,18 @@ public static bool Prefix(IncubatorEgg __instance)
...
-            __instance.Invoke("PlayFxOnBaby", 2f);
         }
         else
         {
-            // Non-simulating player: just play the egg animation
-            // The baby will be spawned by server broadcast and SeaEmperorBaby_Start_Patch
-            // will make it swim to mother
-            SafeAnimator.SetBool(__instance.animationController.eggAnimator, __instance.animParameter, true);
+            // Non-simulating player: mark baby as temporary (will be cleaned up after animation)
+            baby.name += "_NitroxTemporary";
```
Comment (dartasen) [inline NitroxPatcher/Patches/Dynamic/IncubatorEgg_HatchNow_Patch.cs]: You should probably have an internal constant, so other patches can use it.

Will avoid oopsies if someone change it one day

**Comment by Measurity** [comment]
Added test steps to PR. Works decently well on both players only two things:
- Babies movement isn't smooth, probably conflicting with entity position and animation logic.
- Sea emperor position not synced but plays out individually.

Merging this now as it's good improvement.
