### PR TITLE
Fix modules disappearing when swapping between slots

### LINKED ISSUE #2330: Switching the slot of a battery or power cell in a charger causes it to disappear
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Epic

### Describe the issue.

If a battery/cell is already inside of a charger and you drag it into a different slot, it will disappear a majority of the time. This only seems to happen when at least 2 people are connected to the server.

The patched method Equipment.RemoveItem runs an unusual amount of times when this happens (3, when 1 would be expected), which broadcasts a packet each time.

I am confident that this issue is unrelated to #2318.

### Describe the steps you took to encounter the bug.

Make sure there are at least two people connected. I used two instances of Subnautica running on one computer.
Put a battery inside of a battery charger. 
Drag it from its current slot into any other slot. 

### Relevant log output

No relevant log data

### PR DESCRIPTION
**Pull request by SpaceMonkeyy86**
Fixes #2330

### CODE REVIEW

File: NitroxClient/GameLogic/Entities.cs [hunk 1]
```diff
@@ -277,6 +269,14 @@ public static void DestroyObject(GameObject gameObject)
                 return;
             }
 
+            if (gameObject.TryGetComponent(out Pickupable pickupable))
```
Comment (tornac1234) [inline NitroxClient/GameLogic/Entities.cs:272]: Would add a comment to explain that we trigger this early so we can suppress it and that this code will not run twice if it's already null

File: NitroxClient/GameLogic/Spawning/InventoryItemEntitySpawner.cs [hunk 2]
```diff
@@ -47,7 +47,7 @@ protected override bool SpawnSync(InventoryItemEntity entity, TaskResult<Optiona
         }
         if (!CanSpawn(entity, out GameObject parentObject, out ItemsContainer container, out string errorLog))
         {
-            Log.Error(errorLog);
+            Log.Info(errorLog);
```
Comment (tornac1234) [inline NitroxClient/GameLogic/Spawning/InventoryItemEntitySpawner.cs]: Why would you change that

File: NitroxServer/Communication/Packets/Processors/ModuleRemovedProcessor.cs [hunk 3]
```diff
@@ -31,6 +31,9 @@ public override void Process(ModuleRemoved packet, Player player)
 
             if (entity.Value is InstalledModuleEntity installedModule)
             {
+                // packet.NewParentId is actually the old container, so when the old equipment grid wasn't the player equipment,
```
Comment (Jannify) [inline NitroxServer/Communication/Packets/Processors/ModuleRemovedProcessor.cs:34]:
```suggestion
                // TODO: packet.NewParentId is actually the old container, so when the old equipment grid wasn't the player equipment,
```

File: NitroxClient/GameLogic/Spawning/InventoryItemEntitySpawner.cs (hunk 2 above)
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/Spawning/InventoryItemEntitySpawner.cs]: The corresponding line in SpawnAsync uses Log.Info. Also, this line prints "Could not find container field on GameObject" when another player removes any module, so I wanted to clarify that this is known behavior and not a bug.

Comment (Coding-Hen) [reply NitroxClient/GameLogic/Spawning/InventoryItemEntitySpawner.cs]: If this is known behaviour and not a bug or something we are worried about do we even need a log?

Comment (tornac1234) [reply NitroxClient/GameLogic/Spawning/InventoryItemEntitySpawner.cs]: Both logs are actual errors happening, whether it's a known behaviour or not (something broke so we need to notify it as an error). It's my bad for writing Log.Info in SpawnAsync though 😅 both should be Log.Error

**Review by Jannify — COMMENTED** [review]
:( :O
