### PR TITLE
Fully sync exosuits and drilling

### LINKED ISSUE #2278: Prawn suit drilling doesn't save raw materials globally
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

The materials that i got from drilling are only local.
Other players cannot see the materials, regardless of where I move or store them.
After reconnect the materials are gone.
 Tested IG with a friend.

### Describe the steps you took to encounter the bug.

1. Spawn prawn suit
2. Put  drilling arm on prawn suit
3. Find large resource deposit and drill  it
4. Check prawns storage
5. Player 1 can see the resources but Player 2 cant

### Relevant log output

_No response_

### LINKED ISSUE #2303: Errors in logs when adding and removing modules
### Describe the issue

- Join a world with two players
- Spawn a seamoth or exosuit, then try to add or remove upgrades or arms
```
[16:42:34.924] [ERR-UNITY] Unregistering id 'd101f923-5850-4d02-af34-497d3203daa6' (class 'cfea2a50-6fc1-41f7-b496-a36a31b0639f', registered class 'cfea2a50-6fc1-41f7-b496-a36a31b0639f') failed because it already changed to 'ExosuitDrillArmModule(Clone)' at (39.2, -14.8, -283.2), used to be 'ExosuitDrillArmModule(Clone)' at (38.2, -12.1, -283.3)
[16:42:35.825] [ERR-UNITY] Unregistering id '2d7a8a1c-872c-49da-949f-00bba9e0a7cf' (class 'ce9e25f2-b062-4c3d-bf10-abc1f08ad2f7', registered class 'ce9e25f2-b062-4c3d-bf10-abc1f08ad2f7') failed because it already changed to 'ExosuitGrapplingArmModule(Clone)' at (39.2, -14.8, -283.2), used to be 'ExosuitGrapplingArmModule(Clone)' at (38.2, -12.1, -283.3)
[16:43:24.886] [DBG] Received: Added item ExosuitDrillArmModule (d101f923-5850-4d02-af34-497d3203daa6) to container Landscape/Global Root/Exosuit(Clone)
[16:43:24.893] [ERR-UNITY] Unregistering id 'd101f923-5850-4d02-af34-497d3203daa6' (class 'cfea2a50-6fc1-41f7-b496-a36a31b0639f', registered class 'cfea2a50-6fc1-41f7-b496-a36a31b0639f') failed because it already changed to 'ExosuitDrillArmModule(Clone)' at (37.6, -12.5, -283.6), used to be 'ExosuitDrillArmModule(Clone)' at (39.2, -14.8, -283.2)
[16:43:25.264] [DBG] Received: Added item ExosuitGrapplingArmModule (2d7a8a1c-872c-49da-949f-00bba9e0a7cf) to container Landscape/Global Root/Exosuit(Clone)
[16:43:25.268] [ERR-UNITY] Unregistering id '2d7a8a1c-872c-49da-949f-00bba9e0a7cf' (class 'ce9e25f2-b062-4c3d-bf10-abc1f08ad2f7', registered class 'ce9e25f2-b062-4c3d-bf10-abc1f08ad2f7') failed because it already changed to 'ExosuitGrapplingArmModule(Clone)' at (37.6, -12.5, -283.6), used to be 'ExosuitGrapplingArmModule(Clone)' at (39.2, -14.8, -283.2)
```
^ Added a drill arm and grappling arm to an exosuit, then removed them in that order

Additionally, `Equipment_RemoveItemPatch` appears to incorrectly set the new parent id of the item to the id of the former parent, which could cause problems with nuclear reactors or cyclops decoy loading tubes (untested).

These errors don't cause any user-facing issues, but they might lead to problems in the future.

### LINKED ISSUE #2386: Rework module removal
### Describe the issue

As of now, as pointed out by @SpaceMonkeyy86, module removal works pretty weirdly (e.g. it has a NewParentId which points to its old container) and ModuleRemovedProcessor.cs (server-side) has weird functionning towards it.

I think we should list the different causes of module removal and either treat those as a module reparent (when a module is switched in another slot) or as a proper module unequip (I like this wording better) in which case there'd be both an ParentId and a NewParentId, which would make it clear that the module is becoming a simple item in someone's inventory

### LINKED ISSUE #2488: Desynced Prawn Suit storage
### Which version are you playing on?

1.8.0.0 (Latest release)

### Details about version

_No response_

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

The storage of the prawnsuit appears to be empty to the player not piloting the prawn suit

### Describe the steps you took to encounter the bug.

1. Player 1 pilots the prawn suit and mines some ore
2. The player 2 tries to access the prawn suit storage when player 1 finishes mining
3. For player 2 the storage is empty, for player 1 is full of ore

### Relevant log output

_No response_

### LINKED ISSUE #2577: Creature Decoy Upgrade Slots not synced.
### Which version are you playing on?

1.8.0.1 (Latest release)

### Details about version

1.8.0.1

### Which OS are you playing on?

Linux

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

When you prefill the creature decoy on the cyclops with 5 canisters and then log out. When you log back in only one creature decoy remains.

### Describe the steps you took to encounter the bug.

Get a cyclops. Get creature Decoy upgrade module. Plug it in. Craft 5 creature decoy's. Fill them in the cyclops tube. Log out. Log back in. 1 decoy remaining.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SpaceMonkeyy86**
- [x] Sync claw arms
- [x] Sync picking up items with claw arms
- [x] Sync drill arms
- [x] Sync drill arm position when drilling (automatically moves down to deposit)
- [x] Sync grappling arms
- [x] Sync grappling hook from grappling arms
- [x] Sync propulsion arms
- [x] Sync torpedo arms
- [x] Sync exosuit power cells
- [x] Sync drillable deposits visually disappearing in parts when drilled
- [x] Sync resources spawning from drillable deposits
- [x] Sync "pinata" resources automatically going into vehicle storage
- [x] Sync respawning ion cube deposit in primary containment facility antechamber
- [x] Persist destroyed status of deposits when saving

Fixes #2278, fixes #2303, fixes #2386, fixes #2577

### CODE REVIEW

**Comment by leonidasjan** [comment]
GJ on the PR @SpaceMonkeyy86 

I found 4 bugs that u might have missed

1.  The second power cell in the exosuit isn’t synced at all.
2.  If you swap an arm from one slot to another, it first vanishes for everyone, then reappears—but only for the second player.
3.  If you repeatedly equip and unequip an arm, it can sometimes duplicate (this might be just lag but i can do it consistently).

4.  The other player can still hear some sounds from the exosuit when the other player is far away (like 0,5km away).  When u let go of the spacebar, they can hear for split second the jetpack/engine "revving off".  Occasionally they can also hear a loud stomp from the exosuit.

Everything else works great :D. Keep up the good work

**Comment by leonidasjan** [comment]
Good work on the bug fixes @SpaceMonkeyy86 😄 

The bugs i listed are gone (except for the sound issues but i understand that its for the future).

The only thing ive noticed is that there are still some bugs while grabbing another player with the hook. If you want u can fix those issues but IMO grabbing other players should be disabled cause its a little weird.

from the bug testing perspective the pr is ready to merge

**Comment by SpaceMonkeyy86** [comment]
@leonidasjan Thanks, it should be impossible for other players to be hit with the grappling hook now.

**Comment by leonidasjan** [comment]
LGTM 👍

**Comment by dartasen** [comment]
Looks good from what I've seen IG, thank's for the PR

We noticed few things we noticed yesterday during test sessions : 
* Seems to have some issue with global sound while an exosuit is walking
* Exosuit spawns with only one battery filled in
* We noticed some duplication/desync issue upon relog with deposits, might need some more deep testing on that part

**Comment by SpaceMonkeyy86** [comment]
Merging #2137 created a lot of merge conflicts with this PR since both of them completely rewrote a lot of the same subsystems code. I will need to do some more work to get everything back to a working state, then we need re-reviews and more in-game testing.

**Comment by SpaceMonkeyy86** [comment]
Never mind, that was suspiciously easy. We definitely need some in-game tests because I have a hard time believing everything is still working after that.

**Comment by OhmV-IR** [comment]
Test results(May 6 2025):
- Disabling pvp does not disable gas damage from torpedoes fired by other players(minor, for 1.9 or future)
- Beam of propulsion arm is not synced(minor, leave for future)
- Exosuit entering into moonpool anim does not sync, packet sends but is not effected on other client for some reason, once other player gets in the exosuit it warps to the pos though(major, must fix)
- Similar issue with undocking
- Ion cube pillar spinning and lowering in antechamber is not synced(minor, for 1.9 or future)
- Position of drill arms relative to ore that is being mined is way off(not sure if fixable, probably 1.9)

**Comment by SpaceMonkeyy86** [comment]
Results from in-game testing:
- "Couldn't find entity for ___" errors in server when swapping arms (sync still works)
- SFX of drill whirring is audible everywhere for other players
- Torpedos deal damage to other players even when PvP is off
- VFX of beam connecting propulsion arm to object is not synced
- When entering a moonpool, the exosuit usually stays outside for other players until the player enters it (then it immediately docks)
- Leaving a moonpool is usually not synced
- VFX of drill colliding with deposit is not synced
- Drill arm does not physically touch the deposit when drilling (vanilla bug, probably intended, maybe fix?)

All are very minor / wontfix except the moonpool issues

**Comment by SpaceMonkeyy86** [comment]
The docking and undocking issues were found to be unrelated to this PR, and the other fixes are not necessary for 1.8, so this PR should be considered all good regarding in-game tests.

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+            if (oldTotalHealth > 0 && totalHealth <= 0)
+            {
+                drillable.SpawnFX(drillable.breakAllFX, chunkPos);
+
+                // Only use of Drillable.onDrilled, saves having to use reflection to invoke it
+                if (drillable.TryGetComponentInParent(out AnteChamber antechamber))
+                {
+                    antechamber.OnDrilled(drillable);
+                }
+            }
```
Comment (Jannify) [inline NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs:62]: This is kind confusing for me. Could you maybe write 1-2 lines what the goal of the code is?

File: NitroxClient/GameLogic/ExosuitModuleEvent.cs [hunk 2]
```diff
@@ -113,20 +111,46 @@ public static void UseGrappling(ExosuitGrapplingArm grapplingArm, ExosuitArmActi
...
                 break;
         }
     }
+
+    public static void UsePropulsion(ExosuitPropulsionArm propulsionArm, ExosuitArmAction armAction)
+    {
+        switch (armAction)
+        {
+            case ExosuitArmAction.START_USE_TOOL:
+                propulsionArm.propulsionCannon.animator.SetBool("use_tool", true);
```
Comment (Jannify) [inline NitroxClient/GameLogic/ExosuitModuleEvent.cs:129]:
```suggestion
                propulsionArm.propulsionCannon.animator.SetBool(useToolAnimation, true);
```
Can use this for all following cases

File: NitroxClient/GameLogic/EquipmentSlots.cs [hunk 3]
```diff
@@ -34,19 +42,26 @@ public void BroadcastEquip(Pickupable pickupable, GameObject owner, string slot)
...
-            packetSender.Send(moduleAdded);
+            string classId = pickupable.RequireComponent<PrefabIdentifier>().ClassId;
+            NitroxTechType techType = pickupable.GetTechType().ToDto();
+            EntityMetadata metadata = entityMetadataManager.Extract(pickupable.gameObject).OrNull();
+
+            InstalledModuleEntity moduleEntity = new(slot, classId, itemId, techType, metadata, ownerId, []);
+
+            if (packetSender.Send(new EntitySpawnedByClient(moduleEntity, true)))
+            {
+                Log.Debug($"Sent: Added module {pickupable.GetTechType()} ({itemId}) to equipment {owner.GetFullHierarchyPath()} in slot {slot}");
```
Comment (Jannify) [inline NitroxClient/GameLogic/EquipmentSlots.cs:53]: How spam-y is this logging?

File: NitroxClient/Communication/Packets/Processors/GrapplingHookMovementProcessor.cs [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
+        switch (packet.ArmSide)
+        {
+            case Exosuit.Arm.Left:
+                arm = exosuit.leftArm;
+                break;
+            case Exosuit.Arm.Right:
+                arm = exosuit.rightArm;
+                break;
+        }
```
Comment (Jannify) [inline NitroxClient/Communication/Packets/Processors/GrapplingHookMovementProcessor.cs:26]: Would use `IExosuitArm arm = packet.ArmSide == Exosuit.Arm.Left ? exosuit.leftArm : exosuit.rightArm;` like in `ExosuitArmActionProcessor`

**Review by Jannify — CHANGES_REQUESTED** [review]

File: NitroxClient/GameLogic/ItemContainers.cs [hunk 5]
```diff
@@ -91,22 +91,36 @@ public void AddItem(GameObject item, NitroxId containerId)
...
-        if (!parent.TryGetIdOrWarn(out NitroxId parentId))
+
+        NitroxEntity parent = energyMixin.gameObject.FindAncestor<NitroxEntity>();
+        if (!parent)
         {
+            Log.Warn($"Battery entity {id} is not attached to an entity");
             return;
         }
 
+        EnergyMixin[] components = parent.gameObject.GetAllComponentsInChildren<EnergyMixin>();
```
[the remark this answers is not in the document]
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/ItemContainers.cs:108]: That's what this does, `GetAllComponentsInChildren()` is a wrapper around `GetComponentsInChildren(includeInactive: true)`.

File: NitroxClient/GameLogic/Spawning/InstalledBatteryEntitySpawner.cs [hunk 6]
```diff
@@ -80,7 +81,6 @@ private void SetupObject(GameObject gameObject, EnergyMixin energyMixin)
         energyMixin.Initialize();
         energyMixin.RestoreBattery();
 
-        using (PacketSuppressor<EntityReparented>.Suppress())
```
[the remark this answers is not in the document]
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/Spawning/InstalledBatteryEntitySpawner.cs:83]: I deleted the packet, then added it back and forgot to add back the suppressor. I will add it back 👍

File: NitroxPatcher/Patches/Dynamic/ExosuitTorpedoArm_TryShoot_Patch.cs [hunk 7]
```diff
@@ -0,0 +1,17 @@
...
+
+namespace NitroxPatcher.Patches.Dynamic;
+
+public sealed partial class ExosuitTorpedoArm_TryShoot_Patch : NitroxPatch, IDynamicPatch
+{
+    private static readonly MethodInfo TARGET_METHOD = Reflect.Method((ExosuitTorpedoArm t) => t.TryShoot(out Reflect.Ref<float>.Field, default));
+
+    public static void Postfix(ExosuitTorpedoArm __instance)
+    {
+        ExosuitArmAction action = __instance.animator.GetBool("use_tool") ? ExosuitArmAction.START_USE_TOOL : ExosuitArmAction.END_USE_TOOL;
```
[the remark this answers is not in the document]
Comment (SpaceMonkeyy86) [reply NitroxPatcher/Patches/Dynamic/ExosuitTorpedoArm_TryShoot_Patch.cs:14]: Why is this preferred over passing the string directly?

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs (hunk 1 above)
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs:62]: This updates the health of all nodes in the deposit to the new values in the packet, and spawns any VFX the same way the vanilla code would.

File: NitroxClient/GameLogic/EquipmentSlots.cs (hunk 3 above)
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/EquipmentSlots.cs:53]: Not very, it only triggers if you add or remove modules from a vehicle which is fairly uncommon. It's also a debug message so most people won't see it.

File: NitroxClient/GameLogic/ItemContainers.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (Jannify) [reply NitroxClient/GameLogic/ItemContainers.cs]: Ah, ok. Didn't read the "All".

File: NitroxPatcher/Patches/Dynamic/ExosuitTorpedoArm_TryShoot_Patch.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (Jannify) [reply NitroxPatcher/Patches/Dynamic/ExosuitTorpedoArm_TryShoot_Patch.cs:14]: Performance reasons. If you pass the string the internal hash gets calculated every time

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs (hunk 1 above)
Comment (Jannify) [reply NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs:62]: I meant as a comment in the file :D

Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs:62]: Oh. Yeah no problem 😄

**Comment by dartasen** [comment]
Now that 1.8 is on a branch, we can now give it a deeper look. If you mind rebasing 😄

**Review by Measurity — APPROVED** [review]
Claw arm items pickup isn't synced immediately with remote player but items are there on rejoin.

**Comment by SpaceMonkeyy86** [comment]
Fixed claw arm pickups, ready for review

File: NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs [hunk 8]
```diff
@@ -90,5 +90,7 @@ private void SetupObject(InstalledModuleEntity entity, GameObject gameObject, Ga
         equipment.UpdateCount(pickupable.GetTechType(), true);
         Equipment.SendEquipmentEvent(pickupable, 0, parentObject, entity.Slot);
         equipment.NotifyEquip(entity.Slot, inventoryItem);
+
+        Log.Debug($"Received: Added module {pickupable.GetTechType()} ({entity.Id}) to equipment {parentObject.GetFullHierarchyPath()} in slot {entity.Slot}");
```
Comment (Jannify) [inline NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs:94]: Original sound a little strange
```suggestion
        Log.Debug($"Received: Added module {pickupable.GetTechType()} to ({entity.Id})'s equipment {parentObject.GetFullHierarchyPath()} in slot {entity.Slot}");
```

File: NitroxPatcher/Patches/Dynamic/ExosuitGrapplingArm_OnUseUp_Patch.cs [hunk 9]
```diff
@@ -10,6 +10,6 @@ public sealed partial class ExosuitGrapplingArm_OnUseUp_Patch : NitroxPatch, IDy
 
     public static void Prefix(ExosuitGrapplingArm __instance)
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/ExosuitGrapplingArm_OnUseUp_Patch.cs:11]: Is there a reason some arm patches are prefix and other postfix? Is there a reason to not make them all postfix? @team do we have a guideline what patch to use if it's not important?

File: NitroxPatcher/Patches/Dynamic/Drillable_Restore_Patch.cs [hunk 10]
```diff
@@ -0,0 +1,18 @@
...
+using Nitrox.Model.DataStructures;
+using NitroxClient.GameLogic;
+
+namespace NitroxPatcher.Patches.Dynamic;
+
+public sealed partial class Drillable_Restore_Patch : NitroxPatch, IDynamicPatch
+{
+    public static readonly MethodInfo TARGET_METHOD = Reflect.Method((Drillable t) => t.Restore());
+
+    public static void Postfix(Drillable __instance)
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/Drillable_Restore_Patch.cs:12]: Afais This is only used in the AnteChamber. Would maybe add a comment if it is that way. On the other hand, do we need to check for locks here or is this done on the antechamber side?

File: NitroxClient/GameLogic/ExosuitModuleEvent.cs [hunk 11]
```diff
@@ -8,17 +7,20 @@ namespace NitroxClient.GameLogic;
 
 public class ExosuitModuleEvent
 {
-    private static readonly int useToolAnimation = Animator.StringToHash("use_tool");
-    private static readonly int bashAnimation = Animator.StringToHash("bash");
+    public static readonly int useToolAnimation = Animator.StringToHash("use_tool");
+    public static readonly int bashAnimation = Animator.StringToHash("bash");
```
Comment (Jannify) [inline NitroxClient/GameLogic/ExosuitModuleEvent.cs]:
```suggestion
    public static readonly int UseToolAnimation = Animator.StringToHash("use_tool");
    public static readonly int BashAnimation = Animator.StringToHash("bash");
```

File: NitroxClient/GameLogic/ExosuitModuleEvent.cs [hunk 12]
```diff
@@ -8,17 +7,20 @@ namespace NitroxClient.GameLogic;
...
-    public ExosuitModuleEvent(IPacketSender packetSender)
+    public ExosuitModuleEvent(IPacketSender packetSender, SimulationOwnership simulationOwnership)
     {
         this.packetSender = packetSender;
+        this.simulationOwnership = simulationOwnership;
     }
 
-    public void BroadcastClawUse(ExosuitClawArm clawArm, float cooldown)
+
+    public void BroadcastClawUse(Exosuit exosuit, ExosuitClawArm clawArm, float cooldown)
```
Comment (Jannify) [inline NitroxClient/GameLogic/ExosuitModuleEvent.cs]: Would this maybe be something to move to the patch? That way all patches use the unified `BroadcastArmAction()` method

File: NitroxClient/GameLogic/Items.cs [hunk 13]
```diff
@@ -24,10 +22,11 @@ public class Items
...
 
     /// <summary>
-    /// Whether or not <see cref="Inventory.Pickup"/> is running. It's useful to discriminate between Inventory.Pickup from
-    /// a regular <see cref="Pickupable.Pickup"/>
+    /// Whether or not <see cref="Inventory.Pickup"/> or a similar method is running (if greater than 0).
+    /// It's useful to make the distinction between picking up items and normal item container transfers.
     /// </summary>
-    public bool IsInventoryPickingUp;
+
+    public int PickingUpCount;
```
Comment (Jannify) [inline NitroxClient/GameLogic/Items.cs:29]: Would it make sense to wrap this in an IDisposable to reduce the risk of increasing but never decreasing the counter?

File: NitroxPatcher/Patches/Dynamic/ExosuitClawArm_OnPickupAsync_Patch.cs [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+            Pickupable pickupable = exosuit.GetActiveTarget().GetComponent<Pickupable>();
+            PickPrefab pickPrefab = exosuit.GetActiveTarget().GetComponent<PickPrefab>();
+
+            if (pickupable != null && pickupable.isPickupable && exosuit.storageContainer.container.HasRoomFor(pickupable))
+            {
+                NitroxServiceLocator.LocateService<Items>().PickedUp(pickupable.gameObject, pickupable.GetTechType(), id);
+            }
+            else if (pickPrefab != null)
+            {
+                Log.Debug("Delete Pickprefab for exosuit claw arm"); // what does this mean??
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/ExosuitClawArm_OnPickupAsync_Patch.cs]: If nobody know what it means, yeet it i guess?

File: NitroxPatcher/Patches/Dynamic/ExosuitClawArm_OnPickupAsync_Patch.cs [hunk 15]
```diff
@@ -0,0 +1,46 @@
...
+
+namespace NitroxPatcher.Patches.Dynamic;
+
+public sealed partial class ExosuitClawArm_OnPickupAsync_Patch : NitroxPatch, IDynamicPatch
+{
+    public static readonly MethodInfo TARGET_METHOD = Reflect.Method((ExosuitClawArm t) => t.OnPickupAsync(default, default, default));
+
+    public static IEnumerator Postfix(IEnumerator __result, ExosuitClawArm __instance)
+    {
+        Exosuit exosuit = __instance.GetComponentInParent<Exosuit>();
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/ExosuitClawArm_OnPickupAsync_Patch.cs]: Are you not able to use `__instance.exosuit`?

File: NitroxClient/GameLogic/EquipmentSlots.cs [hunk 16]
```diff
@@ -58,15 +70,8 @@ public void BroadcastUnequip(Pickupable pickupable, GameObject owner, string slo
         }
         else
         {
-            // Reactor rod can't be unequipped so this will only happen when a Nuclear Reactor is destroyed (in which case we don't need this code)
-            if (pickupable.GetTechType() == TechType.ReactorRod)
-            {
-                return;
-            }
-
             // UWE also sends module events here as they are technically equipment of the vehicles.
```
Comment (Jannify) [inline NitroxClient/GameLogic/EquipmentSlots.cs]: As we don't discriminate that hard anymore between modules and items I would remove this comment (same for `BroadcastEquip()`). Or does "module events" mean something special?

File: NitroxPatcher/Patches/Dynamic/Drillable_OnDrill_Patch.cs [hunk 17]
```diff
@@ -0,0 +1,43 @@
...
+    public static void Postfix(Drillable __instance)
+    {
+        if (__instance.TryGetNitroxId(out NitroxId id))
+        {
+            Resolve<Entities>().EntityMetadataChanged(__instance, id);
+            return;
+        }
+
+        // For some reason the drillable ion cube deposit in the primary containment facility
+        // is not automatically tagged as an entity. We spawn it here as a workaround.
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/Drillable_OnDrill_Patch.cs:28]: Would at least add a TODO: that this should be moved to a spawn bootstrapper inside the server

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs [hunk 18]
```diff
@@ -0,0 +1,67 @@
...
+using UnityEngine;
+
+namespace NitroxClient.GameLogic.Spawning.Metadata.Processor;
+
+public class DrillableMetadataProcessor : EntityMetadataProcessor<DrillableMetadata>
+{
+    public override void ProcessMetadata(GameObject gameObject, DrillableMetadata metadata)
+    {
+        Drillable drillable = gameObject.GetComponent<Drillable>();
+        if (!drillable)
```
Comment (Jannify) [inline NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs]: Minor:

```suggestion
        if (!gameObject.TryGetComponent(out Drillable drillable))
```

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs [hunk 19]
```diff
@@ -0,0 +1,67 @@
...
+
+        drillable.timeLastDrilled = metadata.TimeLastDrilled;
+
+        if (drillable.health == null)
+        {
+            drillable.health = metadata.ChunkHealth;
+            return;
+        }
+
+        Validate.IsTrue(drillable.health.Length == metadata.ChunkHealth.Length);
```
Comment (Jannify) [inline NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs]: I think `Validate.IsTrue` can be dangerous here as depending on the caller the next try catch is far away.

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs [hunk 20]
```diff
@@ -0,0 +1,67 @@
...
+            if (oldTotalHealth > 0 && totalHealth <= 0)
+            {
+                drillable.SpawnFX(drillable.breakAllFX, chunkPos);
+
+                // Only use of Drillable.onDrilled, saves having to use reflection to invoke it
+                if (drillable.TryGetComponentInParent(out AnteChamber antechamber))
+                {
+                    antechamber.OnDrilled(drillable);
+                }
+            }
```
Comment (Jannify) [inline NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs:66]: Is it really needed to have this inside the loop? To me it seems more like a after-applying-all-health-values check.

**Review by Jannify — CHANGES_REQUESTED** [review]

File: NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs (hunk 8 above)
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs:94]: `entity.Id` refers to the id of the module, your suggestion implies it's the id of the parent. Did you mean something like `to the equipment of {parentObject.GetFullHierarchyPath()}`?

File: NitroxPatcher/Patches/Dynamic/ExosuitGrapplingArm_OnUseUp_Patch.cs (hunk 9 above)
Comment (SpaceMonkeyy86) [reply NitroxPatcher/Patches/Dynamic/ExosuitGrapplingArm_OnUseUp_Patch.cs:11]: They all use prefix unless postfix is required or if the patch reads fields that were modified inside the original method.

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs (hunk 20 above)
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/Spawning/Metadata/Processor/DrillableMetadataProcessor.cs:66]: The VFX needs to be spawned at the position of the last node that was damaged, so it needs to be inside the loop. This code can only run once however, and in practice only one node will ever be damaged at a time anyway.

File: NitroxPatcher/Patches/Dynamic/Drillable_Restore_Patch.cs (hunk 10 above)
Comment (SpaceMonkeyy86) [reply NitroxPatcher/Patches/Dynamic/Drillable_Restore_Patch.cs:12]: In theory we would need to check for locks here but it doesn't really matter. Even if each player sends this packet it can't start a packet loop or cause a desync, and this case is infrequent enough for the bandwidth use to be negligible. Drillable entities don't use locks at all, so I'm inclined to leave it as is so we don't risk accidental desync from no one having the lock.

File: NitroxClient/GameLogic/Items.cs (hunk 13 above)
Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/Items.cs:29]: I don't think that's necessary, both uses of this variable use a finalizer or try/finally block to decrement. Incrementing in a prefix and decrementing in a finalizer is easier than keeping an IDisposable around for the length of the method call.

File: NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs (hunk 8 above)
Comment (Jannify) [reply NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs:94]: Ah ok mb. If entity.Id is the module it's fine.

File: NitroxClient/GameLogic/ExosuitModuleEvent.cs (hunk 12 above)
Comment (Jannify) [reply NitroxClient/GameLogic/ExosuitModuleEvent.cs]: Empty method? xD

Comment (SpaceMonkeyy86) [reply NitroxClient/GameLogic/ExosuitModuleEvent.cs]: Oops, it's fixed now

**Review by Jannify — APPROVED** [review]
LGTM CW :D

**Comment by Jannify** [comment]
Does the pr also fix #2303 an #2386 ?

**Comment by SpaceMonkeyy86** [comment]
Found a bug that deletes modules from your inventory once you relog, need to fix before merge

**Comment by SpaceMonkeyy86** [comment]
Fixed.

> Does the pr also fix https://github.com/SubnauticaNitrox/Nitrox/issues/2303 an https://github.com/SubnauticaNitrox/Nitrox/issues/2386 ?

Yes, module removal was reworked and doesn't cause log errors. It now uses a conservative approach where `RemoveItem()` destroys the entity and `AddItem()` respawns it, so it is possible to remove modules without putting them under another container now. That also fixes #2577 and probably also nuclear reactor rods not being consumed (not sure how to test that without going AFK for 80 minutes).

**Review by Measurity — APPROVED** [review]
💯
