### PR TITLE
Fix oxygen pipes

### LINKED ISSUE #2555: Standalone Air pumps only work for the player who placed it
### Which version are you playing on?

1.8.0.1 (Latest release)

### Details about version

_No response_

### Which OS are you playing on?

Linux

### On which platform did you buy Subnautica?

Epic

### Describe the issue.

When placing a standalone air pump (the "deployable" version), only the player who placed it can use it. The other players do not see the bubble particles not does it refill oxygen. They can add pipes to the network, but doing so does not allow them to see or use the air.

Oddly enough, when using a base-attached air pump, whislt there is no bubbles for the other player, it does refill their oxygen, regardless of who attached the air pump and pipes.

### Describe the steps you took to encounter the bug.

We are playing on linux, using an Heroic-launcher (epic game store) installed version of subnautica.

For standalone pump bug:
- Go in game
- Fabricate a pump and some pipes
- Deploy pump, add pipes
- Observe that only the player who placed it can use it

For base pump working observation:
- build a base
- add power
- add base-attached air pump
- add pipe
- observe that the last player to have placed a pipe see the bubbles
- also observe that both player can refill their oxygen

### Relevant log output

No relevant log entry

### PR DESCRIPTION
**Pull request by tornac1234**
## [Fix pumps not being able to deploy on remote players](https://github.com/SubnauticaNitrox/Nitrox/commit/449a6bb6f48a464a7b5af237c92364ad478f0f28)

As pumps had a RemotelyControlled MB attached to them, Rigidbody.isKinematic was set to false each frame, preventing it from being detected as deployed and thus breaking it.
I created RemotelyControlledPipeFloater MB to override the FixedUpdate so that isKinematic is no longer set to false when the floater is finally deployed.

## [Fix oxygen pipes bubble VFX not showing](https://github.com/SubnauticaNitrox/Nitrox/commit/af620b3435314cc013c4fbc9ba0b0af2346ae56e)

VFX could not be properly created when the object was not set to active. Now the bubbles work

## Side stuff
- [x] Fixed query command to also work on GlobalRootEntities
- [x] Added a debug Drawer for VFXController

Fixes #2555

### CODE REVIEW

File: NitroxPatcher/Patches/Dynamic/PipeSurfaceFloater_FixedUpdate_Patch.cs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+     * }
+     */
+    public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
+    {
+        // Insert an instruction right before the Ret
+        return new CodeMatcher(instructions).End()
+                                            .InsertAndAdvance([
+                                                new CodeInstruction(OpCodes.Ldarg_0),
+                                                new CodeInstruction(OpCodes.Call, Reflect.Method(() => StopWatching(default)))
+                                            ]).InstructionEnumeration();
```
Comment (Measurity) [inline NitroxPatcher/Patches/Dynamic/PipeSurfaceFloater_FixedUpdate_Patch.cs:30]: Could a postfix work here?

Comment (tornac1234) [reply NitroxPatcher/Patches/Dynamic/PipeSurfaceFloater_FixedUpdate_Patch.cs:30]: needs to detect the value change of deployed so postfix would need passing value from prefix

**Review by Coding-Hen — APPROVED** [review]
LGTM CW
