### PR TITLE
Prevent Ctrl+C from closing the server

### LINKED ISSUE #1489: Ctrl + C is closing the server
### Bug
When pressing `Ctrl+C` in the server console it stops the server

### Expected
It should clear the line with possible entered commands like in normal command-line-interfaces

### Steps to reproduce
Start the server, type something and press `Ctrl+C`

### PR DESCRIPTION
**Pull request by TwinBuilderOne**
Resolves #1489

### CODE REVIEW

File: NitroxServer-Subnautica/Program.cs [hunk 1]
```diff
@@ -297,7 +297,8 @@ private static bool ConsoleEventCallback(int eventType)
 
     private static void OnCtrlCPressed(object sender, ConsoleCancelEventArgs e)
     {
-        StopServer();
+        // Prevents process from terminating
+        e.Cancel = true;
```
Comment (Jannify) [inline NitroxServer-Subnautica/Program.cs:301]:
```suggestion
        e.Cancel = true; // Prevents process from terminating
        Console.Write("\r" + new string(' ', Console.WindowWidth - 1) + "\r"); // Clears current line
```
