### PR TITLE
Fix warpme command not sending escape pod changed packet

### LINKED ISSUE #2238: Warpme command doesn't seem to broadcast the EscapePodChangePacket
### Describe the issue

By doing the warpme command (without any bases/cyclops) while being outside, no EscapePodChangedPacket is being sent to the server.
image

Does work with Bases & Cyclops, since it's using the Subroot system we already have synced

### PR DESCRIPTION
**Pull request by LeanHydra84**
Fixes issue #2238:

"warpme" command now correctly broadcasts the EscapePodChange packet when teleporting the player into the lifepod.
Adds patch (EscapePod_RespawnPlayer_Patch) to hook the function that respawns the player into the lifepod, either after a death or a "warpme".

Now-redundant code removed from Player_MovePlayerToRespawnPoint_Patch.

### CODE REVIEW

File: NitroxPatcher/Patches/Dynamic/Player_MovePlayerToRespawnPoint_Patch.cs [hunk 1]
```diff
@@ -21,13 +21,8 @@ public static void Postfix(Player __instance)
...
-        Optional<NitroxId> currentEscapePodId = Optional.Empty;
-        if (__instance.currentEscapePod)
-        {
-            currentEscapePodId = __instance.currentEscapePod.GetId();
-        }
-
         Resolve<LocalPlayer>().BroadcastSubrootChange(currentSubId);
-        Resolve<LocalPlayer>().BroadcastEscapePodChange(currentEscapePodId);
+        
+        // spawning in the escape pod is handled by EscapePod_RespawnPlayer_Patch for cross-functionality with the warpme command
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/Player_MovePlayerToRespawnPoint_Patch.cs:26]:
```suggestion
        // BroadcastEscapePodChange() is handled by EscapePod_RespawnPlayer_Patch for cross-functionality with the warpme command 
```

File: NitroxPatcher/Patches/Dynamic/EscapePod_RespawnPlayer_Patch.cs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+
+namespace NitroxPatcher.Patches.Dynamic;
+
+public sealed partial class EscapePod_RespawnPlayer_Patch : NitroxPatch, IDynamicPatch
+{
+    private static readonly MethodInfo TARGET_METHOD = Reflect.Method((EscapePod t) => t.RespawnPlayer());
+
+    public static void Postfix(EscapePod __instance)
+    {
+        // LifePod.RespawnPlayer() runs both for player respawn (Player.MovePlayerToRespawnPoint()) and for warpme command
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/EscapePod_RespawnPlayer_Patch.cs:16]:
```suggestion
        // EscapePod.RespawnPlayer() runs both for player respawn (Player.MovePlayerToRespawnPoint()) and for warpme command
```

**Review by Jannify — APPROVED** [review]
LGTM CodeWise

File: NitroxPatcher/Patches/Dynamic/EscapePod_RespawnPlayer_Patch.cs (hunk 2 above)
Comment (Coding-Hen) [reply NitroxPatcher/Patches/Dynamic/EscapePod_RespawnPlayer_Patch.cs:16]: Do we not want to get this resolved? Code wise other than this I am content.

**Review by Coding-Hen — CHANGES_REQUESTED** [review]
If we resolve this comment if it needs doing I will approve this

**Review by Coding-Hen — APPROVED** [review]
LGTM
