### PR TITLE
Fix moonpools undocking not working

### LINKED ISSUE #1745: Moon pool causing seamoth desync
### Version

a 1.6.0.0
### Bug

We cannot find the direct reason but have found out that one of our moon pools seems to cause seamoth desync,
this means unless you drop from one specific moon pool the other user wont see your sea moth (They can also die from just hitting it)
### Expected

They should be synced no matter what moon pool you drop from and you should not die suddenly from stuff that doesn't exist
### Steps to reproduce

Have a layout like outs (unsure if the layout location is the cause) [Attached layout below]
image
Bugged moon pool location: 167.1212, -42.06496, 77.18507
Working moon pool location: 163.5879, -42.06496, 97.42337

### PR DESCRIPTION
**Pull request by tornac1234**
There was an error about detecting properly which was the moonpool parent of the VehicleDockingBay
Would fix #1745, #1398 

EDIT: now, each time we rebuild geometry, we also reapply the spawn processor because the gameobjects children were kind of "resetted"

### CODE REVIEW

File: NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs [hunk 1]
```diff
@@ -34,11 +37,42 @@ static BasePieceSpawnProcessor()
...
+
+        public static void ReRunSpawnProcessor(GameObject finishedPiece, NitroxId nitroxId)
+        {
+            if (spawnProcessorsApplied.TryGetValue(nitroxId, out BasePieceSpawnInfos basePieceSpawnInfos))
+            {
+                RunSpawnProcessor(basePieceSpawnInfos.TechType, basePieceSpawnInfos.LatestBase, basePieceSpawnInfos.LatestCell, finishedPiece);
+            }
+        }
+
+        class BasePieceSpawnInfos
```
Comment (Jannify) [inline NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs:64]: Can this be a private struct?

File: NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs [hunk 2]
```diff
@@ -34,11 +37,42 @@ static BasePieceSpawnProcessor()
...
+        private static void RunSpawnProcessor(TechType techType, Base latestBase, Int3 latestCell, GameObject finishedPiece)
+        {
             if (processorsByType.TryGetValue(techType, out BasePieceSpawnProcessor processor))
             {
                 Log.Info($"Found custom BasePieceSpawnProcessor for {techType}");
                 processor.SpawnPostProcess(latestBase, latestCell, finishedPiece);
             }
         }
+
+        public static void ReRunSpawnProcessor(GameObject finishedPiece, NitroxId nitroxId)
```
Comment (Jannify) [inline NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs:56]: Would like to have a comment here when/in what case you need this method

**Review by Jannify — CHANGES_REQUESTED** [review]

**Review by Jannify — APPROVED** [review]
Code wise seems fine. In-game testing with Ninja didn't show any bugs. Needing one review before merging.

**Comment by Jannify** [comment]
I have to pull back my approval, I found a few undocking centered errors in the logs:

[22:57:50.284] [ERR] Error processing packet [VehicleUndocking: VehicleId: 2e95079a-40bb-4393-9020-9284103c00a3, DockId: 053d8a55-f6a8-467c-9cdb-c5f509a4842b, PlayerId: 2, UndockingStart: False]
System.NullReferenceException: Object reference not set to an instance of an object
  at NitroxClient.GameLogic.RemotePlayer.SetVehicle (Vehicle newVehicle) [0x000b1] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.Communication.Packets.Processors.VehicleUndockingProcessor.FinishVehicleUndocking (NitroxModel.Packets.VehicleUndocking packet, Vehicle vehicle, VehicleDockingBay vehicleDockingBay) [0x00076] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.Communication.Packets.Processors.VehicleUndockingProcessor.Process (NitroxModel.Packets.VehicleUndocking packet) [0x00051] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.Communication.Packets.Processors.Abstract.ClientPacketProcessor`1[T].ProcessPacket (NitroxModel.Packets.Packet packet, NitroxModel.Packets.Processors.Abstract.IProcessorContext context) [0x00001] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.MonoBehaviours.Multiplayer.ProcessPackets () [0x00055] in <4bb7ca7b72d74f11940c27f99df4e928>:0

**Comment by tornac1234** [comment]
I tested it after rebasing and it still worked fine

**Review by dartasen — APPROVED** [review]
From the test session we did, he seems to work pretty well without errors in the logs. We found a bug when trying to dock 2 vehicles at the same time but it's something related to the awful subnautica's code, and it can be fixed by restarting the game.
