### PR TITLE
Fix beacons not reappearing after reconnecting

### LINKED ISSUE #2209: Beacon not being displayed after disconnect
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Hello, maybe this issue is already reported but I didn't see if it is.
Here is my problem.
On 1.8.0.0 even with multiple tested build (master branch), or the build from those PR: https://github.com/SubnauticaNitrox/Nitrox/pull/1848 https://github.com/SubnauticaNitrox/Nitrox/pull/2055
The beacon are not being displayed, let me explain, when joining the server, and listen to the radio the beacon appear, but after the client disconnect, nothing will appear, like the previous beacon vanish from the history, so you can't progress in the game.
The logs come from a test on the https://github.com/SubnauticaNitrox/Nitrox/pull/1848, but the issue is the same on every other branch.

### Describe the steps you took to encounter the bug.

Create a server
Listen to the radio
Beacon appear
Disconnect from the server
Reconnect
Beacon will not be there anymore

### Relevant log output

https://pastebin.com/ELc2tEK1 (game)
https://pastebin.com/gMfMv65p (server)

### PR DESCRIPTION
**Pull request by tornac1234**
Closes #2209

### CODE REVIEW

File: NitroxServer/GameLogic/Unlockables/StoryGoalData.cs [hunk 1]
```diff
@@ -26,8 +26,12 @@ public bool RemovedLatestRadioMessage()
             {
                 return false;
             }
-
+            string message = RadioQueue[0];
             RadioQueue.RemoveAt(0);
+
+            // Just like StoryGoalManager.ExecutePendingRadioMessage
+            CompletedGoals.Add("OnPlay" + message);
```
Comment (dartasen) [inline NitroxServer/GameLogic/Unlockables/StoryGoalData.cs:33]:
```suggestion
            CompletedGoals.Add($"OnPlay{message}");
```

File: NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs [hunk 2]
```diff
@@ -90,11 +89,34 @@ private static IEnumerator SetupTrackers(InitialPlayerSync packet)
...
+        {
+            if (completedGoals.Contains(onGoalUnlock.goal))
+            {
+                // Code adapted from OnGoalUnlock.Trigger
+                foreach (UnlockSignalData unlockSignalData in onGoalUnlock.signals)
+                {
+                    unlockSignalData.Trigger(onGoalUnlockTracker);
+                }
+            }
+        }
```
Comment (dartasen) [inline NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs:112]: If we suppress the OnSceneObjectsLoaded, and call onGoalUnlockTracker&coumpoundTracker init by hand, shouldn't it follow the traditional way the game is using to restore his story data ?

File: NitroxServer/GameLogic/Unlockables/StoryGoalData.cs [hunk 3]
```diff
@@ -26,8 +26,12 @@ public bool RemovedLatestRadioMessage()
             {
                 return false;
             }
-
+            string message = RadioQueue[0];
             RadioQueue.RemoveAt(0);
```
Comment (Jannify) [inline NitroxServer/GameLogic/Unlockables/StoryGoalData.cs:30]: Is it possible to use our custom ThreadSafeQueue implementation for this property?

File: NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs [hunk 4]
```diff
@@ -90,11 +89,34 @@ private static IEnumerator SetupTrackers(InitialPlayerSync packet)
...
         techTypesToRemove.ForEach(techType => storyGoalManager.itemGoalTracker.goals.Remove(techType));
-        yield break;
+
+        // OnGoalUnlock might trigger the creation of a signal which is later on set to invisible when getting close to it
+        // the invisibility is managed by PingInstance_Set_Patches and is restored during PlayerPreferencesInitialSyncProcessor
+        // So we still need to recreate the signals at every game launch
+
+        // To avoid having the SignalPing play its sound we just make its notification null while triggering it
+        // (the sound is something like "coordinates added to the gps" or something)
+        PDANotification pdaNotification = onGoalUnlockTracker.signalPrefab.GetComponent<SignalPing>().vo;
```
Comment (Jannify) [inline NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs:99]: Would cache the SignalPing component here

**Review by Jannify — CHANGES_REQUESTED** [review]

**Review by Jannify — APPROVED** [review]
LGTM CW

File: NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs [hunk 5]
```diff
@@ -90,15 +92,39 @@ private static IEnumerator SetupTrackers(InitialPlayerSync packet)
...
+                // Code adapted from OnGoalUnlock.Trigger
+                foreach (UnlockSignalData unlockSignalData in onGoalUnlock.signals)
+                {
+                    unlockSignalData.Trigger(onGoalUnlockTracker);
+                }
+            }
+        }
+        
+        // recover the notification sound
+        prefabSignalPing.vo = pdaNotification;
```
Comment (dartasen) [inline NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs:119]: It isn't trigger by the ongoalUnlockTracker inside the init ?

**Review by dartasen — APPROVED** [review]
Works fine IG

**Review by Coding-Hen — APPROVED** [review]

File: NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs (hunk 5 above)
Comment (tornac1234) [reply NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs:119]: Actually it's not. This is because when the signal is first created in a singleplayer world, its object is saved and stays there so there's no need to recreate it at each restart.
