### PR TITLE
Grant access to steam libraries in sandbox

### LINKED ISSUE #2688: Starting game installed in unusual location doesn't work (Linux, Steam)
### Which version are you playing on?

1.8.1.0 (Latest release) and `master`

### Which OS are you playing on?

Linux

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

My steam games library is installed in an unusual location: `/drives/apps/Games/steamapps/`. This seems to cause the steam sandbox to prevent it from starting via the "allow multiple instances" option which starts the game executable directly.

### Relevant log output

> pv-adverb[1062822]: E: Failed to execute child process “/drives/apps/Games/steamapps/common/Proton 9.0 (Beta)/proton” (No such file or directory)

### PR DESCRIPTION
**Pull request by CodesInChaos**
The Steam Runtime (Pressure Vessel) sandboxes applications and doesn't grant it access to the whole file system. So if `steamapps` is installed in an unusual location, starting proton will fail. This change adds all steam libraries to the locations the game can access.

Fixes #2688

### CODE REVIEW

File: NitroxPatcher/Main.cs [hunk 1]
```diff
@@ -69,9 +69,14 @@ public static void Execute()
         AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve += CurrentDomainOnAssemblyResolve;
 
         Console.WriteLine("Checking if Nitrox should run...");
+        if (string.IsNullOrEmpty(nitroxLauncherDir.Value))
+        {
+            Console.WriteLine($"Nitrox will not load because launcher path was not provided");
+            return;
+        }
```
Comment (dartasen) [inline NitroxPatcher/Main.cs:76]: This check is redundant, Directory.Exists is already looking for null or empty path and returns false in those cases

**Review by Measurity — APPROVED** [review]
Code looks good. Still works on my end so I'll trust it's working also for steam libraries now. Thank you for the PR!

**Comment by CodesInChaos** [comment]
What I don't understand is why it works without including the launcher path in the whitelist, while the same launcher directory causes problems when starting via steam (#2687).

**Review by dartasen — COMMENTED** [review]
Thank's for the PR !

_If you could write down few words about the fix in the PR description, that would be great 😄_ 
EDIT: nvm It's detailed in the issue

File: NitroxPatcher/Main.cs (hunk 1 above)
Comment (Measurity) [reply NitroxPatcher/Main.cs:76]: I think this is fine because the error message becomes more detailed. This one it's not provided at all. Other one it's "does not exist or is inaccessible".

Comment (CodesInChaos) [reply NitroxPatcher/Main.cs:76]: Having a separate check results in a clearer and more specific error message.

**Review by dartasen — APPROVED** [review]

**Comment by CodesInChaos** [comment]
While the error isn't exactly the same it might fix #2352 as well.
