### PR TITLE
Fix creature respawn duplicating entity for good

### LINKED ISSUE #2426: Hundreds of Shuttlebugs.
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Not sure what's triggering the problem, but my game is infested with Shuttlebugs. They just keep spawning, no matter how many are killed.

https://imgur.com/a/44mg6hB

### Describe the steps you took to encounter the bug.

This started happening after the latest Subnautica update. I am running the latest version of Nitrox 1.8.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tornac1234**
The problem was that when we'd broadcast the creation of respawner, we would actually never destroy the fish itself. Thus, when coming back to the zone, you'd have the fish dying again (from the geyser) and then creating yet another respawner.

Fixes #2426

### CODE REVIEW

**Review by dartasen — APPROVED** [review]

File: NitroxServer/Communication/Packets/Processors/RemoveCreatureCorpseProcessor.cs [hunk 1]
```diff
@@ -22,8 +21,6 @@ public RemoveCreatureCorpseProcessor(PlayerManager playerManager, EntitySimulati
 
     public override void Process(RemoveCreatureCorpse packet, Player destroyingPlayer)
     {
-        // TODO: In the future, for more immersion (though that's a neglectable +), have a corpse entity on server-side or a dedicated metadata for this entity (CorpseMetadata)
-        // So that even players rejoining can see it (before it despawns)
```
Comment (Jannify) [inline NitroxServer/Communication/Packets/Processors/RemoveCreatureCorpseProcessor.cs:26]: Do we have an issue for this or do we plan to not do that feature (or is it purely based on cell loading/unloading which I think you are doing)? Anyways I am fine with all as long as it's consciously decided.

File: NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs [hunk 2]
```diff
@@ -32,16 +27,12 @@ public sealed partial class CreatureDeath_OnKillAsync_Patch : NitroxPatch, IDyna
      * 1st injection:
      * gameObject.GetComponent<Rigidbody>().angularDrag = base.gameObject.GetComponent<Rigidbody>().angularDrag * 3f;
      * UnityEngine.Object.Destroy(base.gameObject);
-     * CreatureDeath_OnKillAsync_Patch.BroadcastCookedSpawned(this, gameObject, cookedData); <---- INSERTED LINE
+     * CreatureDeath_OnKillAsync_Patch.BroadcastCookedSpawned(this, gameObject, processed); <---- INSERTED LINE
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs]:
```suggestion
     * CreatureDeath_OnKillAsync_Patch.BroadcastCookedSpawned(this, gameObject); <---- INSERTED LINE
```

File: NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs [hunk 3]
```diff
@@ -32,16 +27,12 @@ public sealed partial class CreatureDeath_OnKillAsync_Patch : NitroxPatch, IDyna
...
      * 
      * 2nd injection:
-     * base.Invoke("RemoveCorpse", this.removeCorpseAfterSeconds);
-     * CreatureDeath_OnKillAsync_Patch.BroadcastRemoveCorpse(this); <---- INSERTED LINE
-     * 
-     * 3rd injection:
-     * this.eatable.SetDecomposes(true);
-     * CreatureDeath_OnKillAsync_Patch.BroadcastCookedSpawned(this.eatable); <---- INSERTED LINE
+     * this.SyncFixedUpdatingState();
+     * CreatureDeath_OnKillAsync_Patch.BroadcastRemoveCorpse(this, processed);  <---- INSERTED LINE
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs]:
```suggestion
     * CreatureDeath_OnKillAsync_Patch.BroadcastRemoveCorpse(this);  <---- INSERTED LINE
```

File: NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs [hunk 4]
```diff
@@ -54,72 +45,56 @@ public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstructio
...
 
-    public static void BroadcastCookedSpawned(CreatureDeath creatureDeath, GameObject gameObject, TechType cookedTechType)
+    public static void BroadcastCookedSpawned(CreatureDeath creatureDeath, GameObject gameObject)
     {
         if (creatureDeath.TryGetNitroxId(out NitroxId creatureId))
         {
             NitroxEntity.SetNewId(gameObject, creatureId);
         }
 
+        TechType processed = TechData.GetProcessed(CraftData.GetTechType(creatureDeath.gameObject));
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs]: Move inside if

File: NitroxServer/Communication/Packets/Processors/RemoveCreatureCorpseProcessor.cs (hunk 1 above)
Comment (tornac1234) [reply NitroxServer/Communication/Packets/Processors/RemoveCreatureCorpseProcessor.cs:26]: This was a bad idea due to bad understanding of the issue in the first place. A corpse will always be destroyed forever as soon as you load it again, so there's no point in knowing about those on server-side as soon as they're a corpse.

**Review by Jannify — APPROVED** [review]
LGTM CW
