### PR TITLE
Fix leaving bench when writing in the chat

### LINKED ISSUE #1707: Chair/bench exit key will be triggered while chatting
If you're sitting on a chair/bench, if you're typing some word like the E default exit key, the exit behaviour will be triggered.

### PR DESCRIPTION
**Pull request by tornac1234**
Would fix #1707

### CODE REVIEW

File: NitroxPatcher/Patches/Dynamic/FreecamController_FreecamToggle_Patch.cs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+namespace NitroxPatcher.Patches.Dynamic
+{
+    public class FreecamController_FreecamToggle_Patch : NitroxPatch, IDynamicPatch
+    {
+        private static readonly MethodInfo TARGET_METHOD = Reflect.Method((FreecamController t) => t.FreecamToggle());
+
+        public static void Postfix(FreecamController __instance)
+        {
+            Resolve<LocalPlayer>().FreecamEnabled = __instance.mode;
```
Comment (dartasen) [inline NitroxPatcher/Patches/Dynamic/FreecamController_FreecamToggle_Patch.cs:14]: What's the point of the state syncing of freecam ? Seems totally out of scope to me

Comment (dartasen) [reply NitroxPatcher/Patches/Dynamic/FreecamController_FreecamToggle_Patch.cs:14]: image

This method is called by freecam command, this should help remove useless state patch

Comment (tornac1234) [reply NitroxPatcher/Patches/Dynamic/FreecamController_FreecamToggle_Patch.cs:14]: i need to verify but doesn't sitting on the bench also sets you as locked ?

**Review by Jannify — APPROVED** [review]
