### PR TITLE
Fix creature respawn duplicating entities

### LINKED ISSUE #2260: Staying near lava geysers for too long causes a ton of smaller dead creatures to flood the geysar, causing extreme lag.
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Me and my friend tried to build some thermal plants (I know, bad idea). But we at least wanted to try.
Unfortunately, fate had it in for us, and we encounterd a fatal flaw with staying too close to a geyser.
Any creatures that spawned near us, would get killed by the lava geyser and then drop down into it, leaving them there.
We stayed for about 30 minutes constantly dying from the heat while placing the thermal generators and swimming back, that by the time we placed the last one, there were over two hundred dead fish.

### Describe the steps you took to encounter the bug.

Stay close to a lava geysar.
Us constantly dying from it and swimming back may have also effected the result and caused the bug.

### Relevant log output

Logs are the same ones from issue #2259

### PR DESCRIPTION
**Pull request by tornac1234**
Fixes #2260

Step to reproduce : `By putting fishes on the geyser, seeing them die, unload zone and reload the zone`

### CODE REVIEW

**Comment by isaacify** [comment]
This was tested with 2 players for 2 hours. I can say this works perfectly fine on a new save. See my comment on [#2260](https://github.com/SubnauticaNitrox/Nitrox/issues/2260#issuecomment-2869334555) for context.

File: NitroxClient/Communication/Packets/Processors/RemoveCreatureCorpseProcessor.cs [hunk 1]
```diff
@@ -34,38 +33,42 @@ public override void Process(RemoveCreatureCorpse packet)
...
-
         // To avoid SpawnRespawner to be called
         creatureDeath.respawn = false;
         creatureDeath.hasSpawnedRespawner = true;
 
         // To avoid the cooked data section
-        bool lastDamageWasHeat = creatureDeath.lastDamageWasHeat;
         creatureDeath.lastDamageWasHeat = false;
 
+        // Receiving this packet means the creature is dead
```
Comment (tornac1234) [inline NitroxClient/Communication/Packets/Processors/RemoveCreatureCorpseProcessor.cs:59]: The goal here is to ensure the fish is 100% dead when turning it into a corpse but without triggering any side-effects like broadcasting packets since we're currently processing one

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/EatableMetadataProcessor.cs [hunk 2]
```diff
@@ -10,12 +12,32 @@ public override void ProcessMetadata(GameObject gameObject, EatableMetadata meta
...
+        else
         {
-            Resolve<LiveMixinManager>().SyncRemoteHealth(liveMixin, 0);
+            Log.Error($"[{nameof(EatableMetadataProcessor)}] Could not find {nameof(Eatable)} on {gameObject.name}");
         }
     }
+
+    private void ProcessMetadata(Eatable eatable, EatableMetadata metadata)
+    {
+        if (eatable.TryGetComponent(out LiveMixin liveMixin) && liveMixin.health > 0)
```
Comment (tornac1234) [inline NitroxClient/GameLogic/Spawning/Metadata/Processor/EatableMetadataProcessor.cs:25]: It might happen that we're directly applying the metadata on a living creature. But this metadata is only applied to dead creatures so we first need to kill it the right way so that we can later apply the decay timing correctly

File: NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs [hunk 3]
```diff
@@ -44,14 +46,13 @@ public sealed partial class CreatureDeath_OnKillAsync_Patch : NitroxPatch, IDyna
...
-        return new CodeMatcher(instructions).MatchEndForward([
+        return new CodeMatcher(instructions).MatchStartForward([
                                                 new CodeMatch(OpCodes.Ldarg_0),
                                                 new CodeMatch(OpCodes.Ldnull),
                                                 new CodeMatch(OpCodes.Stfld),
                                                 new CodeMatch(OpCodes.Br),
                                             ])
-                                            .Advance(1)
-                                            .InsertAndAdvance(new CodeInstruction(OpCodes.Ldarg_0))
+                                            .InsertAndAdvance(new CodeInstruction(OpCodes.Ldloc_1))
```
Comment (tornac1234) [inline NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs:55]: This is my bad, in IEnumerators the current class reference "this" is accessed by Ldloc_1 and not Ldarg_0 (like in a regular function)

File: NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs [hunk 4]
```diff
@@ -85,22 +86,32 @@ public static void BroadcastCookedSpawned(CreatureDeath creatureDeath, GameObjec
             NitroxEntity.SetNewId(gameObject, creatureId);
         }
 
-        Resolve<Items>().Dropped(gameObject, cookedTechType);
+        if (!IsRemotelyCalled)
```
Comment (tornac1234) [inline NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs:89]: Avoid packet echoing

File: NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs [hunk 5]
```diff
@@ -85,22 +86,32 @@ public static void BroadcastCookedSpawned(CreatureDeath creatureDeath, GameObjec
...
+        {
+            Resolve<Items>().Dropped(gameObject, cookedTechType);
+        }
     }
 
     public static void BroadcastRemoveCorpse(CreatureDeath creatureDeath)
     {
-        if (creatureDeath.TryGetNitroxId(out NitroxId creatureId))
+        // This case is expected when CreatureDeath.Spawn happens (calling this) after a metadata processor has already called this
```
Comment (tornac1234) [inline NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs:97]: Just some reordering down there to ensure we avoid packet echoing

File: NitroxPatcher/Patches/Dynamic/LiveMixin_TakeDamage_Patch.cs [hunk 6]
```diff
@@ -49,7 +49,7 @@ public static void Postfix(float __state, LiveMixin __instance, float originalDa
         }
 
         // At this point, if the victim didn't take damage, there's no point in broadcasting it
-        if (__state != __instance.health)
+        if (__state == __instance.health)
```
Comment (tornac1234) [inline NitroxPatcher/Patches/Dynamic/LiveMixin_TakeDamage_Patch.cs:52]: That's a kinda related fix because damage broadcast is important in this PR
