### PR TITLE
Fix remote players' lighting

### LINKED ISSUE #644: [Base] Player shading is incorrect
Players are always shaded as if they were outside causing them to appear pitch black during the night

### PR DESCRIPTION
**Pull request by tornac1234**
Some screenshots of the testing session in the thread ["light fix PR test session"](https://discord.com/channels/525437013403631617/975468417018658847)
(Tested with 3 players and seemed to work as expected)

How the fix works, we add a component named ``SkyApplier`` which goal is to adjust the lighting level of all the renderers inside a model depending on the lighting source.

Will fix #644

### CODE REVIEW

File: NitroxClient/GameLogic/RemotePlayer.cs [hunk 1]
```diff
@@ -268,5 +270,19 @@ private void UpdateEquipmentVisibility()
...
+        /// </summary>
+        private void SetupSkyAppliers()
+        {
+            // SkyAppliers are the components that apply the light effects on gameobjects
+            SkyApplier skyApplier = Body.AddComponent<SkyApplier>();
+            skyApplier.anchorSky = Skies.Auto;
+            skyApplier.emissiveFromPower = false;
+            skyApplier.dynamic = true;
+            skyApplier.renderers = Body.GetComponentsInChildren<SkinnedMeshRenderer>(true);
+            Log.Debug($"Successfully setup Sky Appliers on {PlayerName}");
```
Comment (Jannify) [inline NitroxClient/GameLogic/RemotePlayer.cs:285]: Minor: I wouldn't use the log here. You aren't (and probably can't) check if the SkyAppliers is successfully setup. Therefore this log will show up independent from the success of the method, only exception is a hard throw which would be logged anyway.

**Review by Jannify — CHANGES_REQUESTED** [review]

File: NitroxClient/GameLogic/RemotePlayer.cs (hunk 1 above)
Comment (tornac1234) [reply NitroxClient/GameLogic/RemotePlayer.cs:285]: Maybe I can insert a try catch with a first call to the ``SkyApplier.ApplySkybox()`` method and print if it was successful or an error

Comment (Jannify) [reply NitroxClient/GameLogic/RemotePlayer.cs:285]: The question is do we expect the method to fail? If not we shouldn't try catch it imo.

Comment (tornac1234) [reply NitroxClient/GameLogic/RemotePlayer.cs:285]: The ``SkyApplier.ApplySkybox()`` will fail if the skyApplier isn't correctly setup

Comment (Jannify) [reply NitroxClient/GameLogic/RemotePlayer.cs:285]: Looking at the code I don't see where it could fail as it checks for null for every variable used. Am I missing something?

Comment (tornac1234) [reply NitroxClient/GameLogic/RemotePlayer.cs:285]: I guess it's because of the renderers part, when I first created the function, I didn't include the ``.renderers = ...`` part and for some reasons, errors were thrown and you couldn't even load into the game.

Comment (Jannify) [reply NitroxClient/GameLogic/RemotePlayer.cs:285]: That's true if `renderers` is null it can throw but now that you use `Body.GetComponentsInChildren<SkinnedMeshRenderer>(true)` it should never be null, only not filled with anything in the worst case.

Comment (tornac1234) [reply NitroxClient/GameLogic/RemotePlayer.cs:285]: Ok, I'll just remove the logging then

**Review by dartasen — APPROVED** [review]
