### PR TITLE
Fixed vehicles color and name synchronisation

### LINKED ISSUE #1470: PrawSuit/Seamoth colors are not always persisted

### LINKED ISSUE #1524: Reduce VehicleColorChange packets while selecting color
We are currently sending a `VehicleColorChange` packet each time the cursor moves a pixel (at least for the vehicle upgrade console). To reduce bandwidth we should use the "Done" button and/or leaving the upgrade console.

### PR DESCRIPTION
**Pull request by Bricklou**
Seamoth and exosuit had some update issues between games while updated.

I tested all my change to be sure that color and name are properly updated on: seamoth, exosuit, cyclops and rocket.

Fix #1470
Fix #1524

### CODE REVIEW

File: NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs [hunk 1]
```diff
@@ -18,12 +19,36 @@ public VehicleNameChangeProcessor(IPacketSender packetSender)
...
+                    subNameTarget = vehicleObject.RequireComponentInChildren<SubName>();
+                }
+            }
+            else
+            {
+                subNameInput = vehicleObject.RequireComponentInChildren<SubNameInput>();
+                subNameTarget = subNameInput.target;
+            }
+
+            if (subNameInput != null && subNameTarget != null)
```
Comment (Jannify) [inline NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs:43]:
```suggestion
            if (subNameInput && subNameTarget)
```
Also you should add a error log here so we can now when it's failing

File: NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs [hunk 2]
```diff
@@ -18,12 +19,36 @@ public VehicleNameChangeProcessor(IPacketSender packetSender)
...
+            if (vehicleObject.GetComponent<Vehicle>())
             {
-                subNameInput.OnNameChange(namePacket.Name);
+                if (namePacket.ParentId.HasValue)
+                {
+                    GameObject moonpool = NitroxEntity.RequireObjectFrom(namePacket.ParentId.Value);
+                    GameObject baseCell = moonpool.RequireComponentInParent<BaseCell>().gameObject;
+
+                    subNameInput = baseCell.RequireComponentInChildren<SubNameInput>();
+                    subNameTarget = vehicleObject.RequireComponentInChildren<SubName>();
```
Comment (Jannify) [inline NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs:34]: Can't you use `subNameTarget = subNameInput.target;` here like below?

File: NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs [hunk 3]
```diff
@@ -18,12 +19,36 @@ public VehicleNameChangeProcessor(IPacketSender packetSender)
...
         public override void Process(VehicleNameChange namePacket)
         {
-            GameObject target = NitroxEntity.RequireObjectFrom(namePacket.Id);
-            SubNameInput subNameInput = target.RequireComponentInChildren<SubNameInput>();
+            GameObject vehicleObject = NitroxEntity.RequireObjectFrom(namePacket.VehicleId);
+            SubNameInput subNameInput = null;
+            SubName subNameTarget = null;
 
-            using (packetSender.Suppress<VehicleNameChange>())
+            if (vehicleObject.GetComponent<Vehicle>())
```
Comment (Jannify) [inline NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs:26]: Can't you use `if (namePacket.ParentId.HasValue)` here as it would fail anyway if it's not a vehicle later?

File: NitroxPatcher/Patches/Dynamic/SubNameInput_OnColorChange_Patch.cs [hunk 4]
```diff
@@ -21,25 +22,29 @@ public static void Postfix(SubNameInput __instance, ColorChangeEventData eventDa
             if (subname != null)
```
Comment (Jannify) [inline NitroxPatcher/Patches/Dynamic/SubNameInput_OnColorChange_Patch.cs:22]: Would use this as it checks the components better for null:

        public static void Postfix(SubNameInput __instance, ColorChangeEventData eventData)
        {
            SubName subname = __instance.target;
            if (subname)
            {
                GameObject parentVehicle;
                NitroxId controllerId = null;

                if (subname.TryGetComponent(out Vehicle vehicle))
                {
                    GameObject baseCell = __instance.gameObject.RequireComponentInParent<BaseCell>().gameObject;
                    GameObject moonpool = baseCell.RequireComponentInChildren<BaseFoundationPiece>().gameObject;

                    controllerId = NitroxEntity.GetId(moonpool);
                    parentVehicle = vehicle.gameObject;
                }
                else if (subname.TryGetComponent(out SubRoot subRoot))
                {
                    parentVehicle = subRoot.gameObject;
                }
                else if (subname.TryGetComponent(out Rocket rocket))
                {
                    parentVehicle = rocket.gameObject;
                }
                else
                {
                    Log.Error($"[SubNameInput_OnColorChange_Patch] The GameObject {subname.gameObject.name} doesn't have a Vehicle/SubRoot/Rocket component.");
                    return;
                }

                NitroxId vehicleId = NitroxEntity.GetId(parentVehicle);
                VehicleColorChange packet = new(__instance.SelectedColorIndex, controllerId, vehicleId, eventData.hsb.ToDto(), eventData.color.ToDto());
                NitroxServiceLocator.LocateService<IPacketSender>().Send(packet);
            }
        }

**Review by Jannify — CHANGES_REQUESTED** [review]
I just made comments in either the name or color class but they can be applied on both :D

**Comment by Bricklou** [comment]
@Jannify is this better ?

File: NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs [hunk 5]
```diff
@@ -31,36 +30,29 @@ public override void Process(VehicleColorChange colorPacket)
...
                     // OnColorChange calls these two methods, in order to update the vehicle color and the color+text on the ingame panel, respectively:
-                    subNameTarget.SetColor(colorPacket.Index, colorPacket.HSB.ToUnity(), colorPacket.Color.ToUnity());
+                    subNameInput.target.SetColor(colorPacket.Index, colorPacket.HSB.ToUnity(), colorPacket.Color.ToUnity());
                     subNameInput.SetColor(colorPacket.Index, colorPacket.Color.ToUnity());
-
                 }
                 else
                 {
-                    Log.Error($"[VehicleColorChangeProcessor] The GameObject {vehicleObject.name} doesn't have a Vehicle component");
+                    Log.Error($"[VehicleColorChangeProcessor] SubNameInput or targeted SubName is null.");
```
Comment (tornac1234) [inline NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs:53]: When a player is still on the console and another one leaves the moonpool with the seamoth (for example), the first player still sees the upgrade console available with the color changing and name changing panel. While it should go back to the "Nothing docked" panel. This error will then spam in the logs when changing the color / name (It's the same for the VehicleNameChangeProcessor)

Comment (Bricklou) [reply NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs:53]: Oh, didn't tried to undock the seamoth while testing :open_mouth: 
I will have to check this.

Comment (Jannify) [reply NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs:53]: Isn't that an issue of the undock processor then? Maybe the best place to look at

Comment (Bricklou) [reply NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs:53]: well, I don't know. Should I fix it too in this PR or make a new PR for this (me or someone else) ? :thinking:

Comment (Jannify) [reply NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs:53]: > well, I don't know. Should I fix it too in this PR or make a new PR for this (me or someone else) ? :thinking: 

If you find a fix before it's merged by me/other Gost you can include it here. If not it's not that problematic if you have a null check in the patch to stop the packet spamming even if the ui is "broken" then.

File: NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs [hunk 6]
```diff
@@ -2,10 +2,10 @@
 using NitroxClient.Communication.Packets.Processors.Abstract;
 using NitroxClient.MonoBehaviours;
 using NitroxClient.Unity.Helper;
-using NitroxModel.Helper;
 using NitroxModel.Packets;
 using NitroxModel_Subnautica.DataStructures;
 using UnityEngine;
+using NitroxModel.Logger;
```
Comment (Jannify) [inline NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs:8]: This line isn't sorted into the other usings, I highly recommend [this extension](https://marketplace.visualstudio.com/items?itemName=mynkow.FormatdocumentonSave) for VS.

Comment (Bricklou) [reply NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs]: is this OK now ?

**Review by Jannify — CHANGES_REQUESTED** [review]

**Review by Jannify — APPROVED** [review]

**Comment by dartasen** [comment]
Fixes #1470

**Review by Jannify — APPROVED** [review]

**Comment by tornac1234** [comment]
Will fix [Issue#1524](https://github.com/SubnauticaNitrox/Nitrox/issues/1524)
