### PR TITLE
Fix fabricator crafting sound not playing for remote players

### LINKED ISSUE #2434: Fabricator crafting sound doesn't seem to play
### Describe the issue

Context:  Regressed in #2424 

For remote players, the sound when someone is crafting something in the fabricator (base, cyclops, moonpool, upgrade station ...) does not play

### PR DESCRIPTION
**Pull request by misterbubb**
Fixes #2434

### CODE REVIEW

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/CrafterMetadataProcessor.cs [hunk 1]
```diff
@@ -56,4 +58,38 @@ private static void SpawnItemInCrafter(CrafterLogic crafterLogic, CrafterMetadat
...
+        if (gameObject.TryGetComponentInChildren(out ghostCrafter, true))
+        {
+            return true;
+        }
+
+        if (gameObject.TryGetComponent(out CrafterLogic crafterLogic))
+        {
+            Base parentBase = gameObject.GetComponentInParent<Base>();
+            if (parentBase)
+            {
```
Comment (Jannify) [inline NitroxClient/GameLogic/Spawning/Metadata/Processor/CrafterMetadataProcessor.cs]: Would use early return here for the two ifs to provide better readability.

File: NitroxClient/GameLogic/Spawning/Metadata/Processor/CrafterMetadataProcessor.cs [hunk 2]
```diff
@@ -56,4 +58,38 @@ private static void SpawnItemInCrafter(CrafterLogic crafterLogic, CrafterMetadat
...
+                foreach (GhostCrafter crafter in parentBase.GetComponentsInChildren<GhostCrafter>(true))
```
Comment (Jannify) [inline NitroxClient/GameLogic/Spawning/Metadata/Processor/CrafterMetadataProcessor.cs]: @tornac1234 Is there a better way to find the ghostcrafter in a base?

Comment (tornac1234) [reply NitroxClient/GameLogic/Spawning/Metadata/Processor/CrafterMetadataProcessor.cs]: Supposedly there's a list of ghosts linked to a base (Base.ghosts) but I'm not sure if crafters are added to it

Comment (misterbubb) [reply NitroxClient/GameLogic/Spawning/Metadata/Processor/CrafterMetadataProcessor.cs]: > Supposedly there's a list of ghosts linked to a base (Base.ghosts) but I'm not sure if crafters are added to it

checked Base.ghosts its a List<BaseGhost> for construction ghosts, not crafters GhostCrafter extends Crafter not BaseGhost so we need to use GetComponentsInChildren<GhostCrafter> here
